[[plugins]] # ディレクトリツリーの表示
repo = 'scrooloose/nerdtree'
hook_add = 'nnoremap <silent><C-e> :NERDTreeToggle<CR>'

[[plugins]] # "\c" で スネークケース <-> キャメルケース を変換
repo = 'tyru/operator-camelize.vim'
depends = ['vim-operator-user']
hook_add = 'map <leader>c <plug>(operator-camelize-toggle)'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]] # help の日本語化
repo = 'vim-jp/vimdoc-ja'
hook_add = 'set helplang=ja'

[[plugins]] # vim 上で非同期シェルを実行
repo = 'Shougo/vimshell.vim'
depends = ['vimproc']
hook_add = 'nnoremap vsh :vertical botright terminal<CR>'
hook_source = '''
    let g:vimshell_user_prompt = 'fnamemodify(getcwd(), ":~")'
    let g:vimshell_prompt =  '$ '
'''

[[plugins]]
repo = 'Shougo/vimproc'

[[plugins]] # :QuickRun でバッファ内のコードを実行
repo = 'thinca/vim-quickrun'
hook_source = '''
    let g:quickrun_config = get(g:, 'quickrun_config', {})
    let g:quickrun_config._ = {
        \ 'outputter/buffer/opener': 'new',
        \ 'outputter/buffer/into': 1,
        \ 'outputter/buffer/close_on_empty': 1,
        \ }
'''
